# Generated by Django 3.2.17 on 2023-02-10 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("public_website", "0002_apicall"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apicall",
            old_name="PEid",
            new_name="queried_id",
        ),
    ]
