# Generated by Django 3.2.18 on 2023-03-22 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("public_website", "0005_rename_queried_id_apicall_params"),
    ]

    operations = [
        migrations.CreateModel(
            name="Habilitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=150)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="habilitation",
                        to="auth.group",
                    ),
                ),
            ],
        ),
    ]
