# Generated by Django 3.2.18 on 2023-03-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_website", "0005_rename_queried_id_apicall_params"),
    ]

    operations = [
        migrations.CreateModel(
            name="Habilitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=150)),
            ],
        ),
    ]
