# Generated by Django 3.2.19 on 2023-05-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public_website", "0008_apicall_habilitation"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrestWebhookMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(help_text="When we received the event."),
                ),
                ("payload", models.JSONField(default=None, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name="brestwebhookmessage",
            index=models.Index(
                fields=["received_at"], name="public_webs_receive_7d302f_idx"
            ),
        ),
    ]
