# Generated by Django 3.2.18 on 2023-07-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_website', '0009_alter_habilitation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilitation',
            name='server',
            field=models.TextField(default='https://particulier-test.api.gouv.fr'),
            preserve_default=False,
        ),
    ]
